In [1]:
import numpy as np

# we set a seed to make the results reproducible
np.random.seed(32)


# Gaussian Processes - Exercise Session 1 - Solutions

## Relationship between linear models and conditional Gaussian distribution

In this exercise session, you are going to learn the relationship between the predictions given by a linear model and the mean estimate given by a conditional Gaussian distribution. We will derive both formula step-by-step and you should implement them in Python.


### Dataset creation

We are going to create a toy dataset $D=\{(\mathbf{x_1},y_1),...(\mathbf{x_n},y_n)\}$, where $\mathbf{x} \in \mathbb{R}^3$ and $y \in \mathbb{R}$. The $\mathbf{x}$ is created in the following way:


1.   First we sample a number in $[0,1]$ for each dimension
2.   Then we multiply each dimension with a random integer in the range $[1,20]$

This way, we now have random $x$'s with very different values. Since we want to have a bias term in our linear model, we use the trick of adding a of 1 in front of our $\mathbf{x} \in D$.

The next step is to generate the $y$ for each $\mathbf{x}$. We have to define the real weights vector $\mathbf{w}\in \mathbb{R}^4$ and then compute 
$$y = \mathbf{w}^T \mathbf{x} + \epsilon$$
where $\epsilon$ is the zero-mean and unit variance Gaussian noise.

At this point, we have our datset $D$ ready. We will split it in a training set $\mathbf{X}$ and a test set $\mathbf{X_*}$ (we here will adhere to a typical setting were 80% of the data goes into the training set and the remaining 20% will be reserved for testing. 


<font color='green'> There was some confusion during this exercise about the role of the bias, which translates into the 1 that we are stacking as first column in our dataset.

Suppose we have a dataset $D = \{(x_0,y_0), \dotsc, (x_N,y_N)\}$ where $x_i, y_i \in \mathbb{R}^1$. When we are using linear regression, we are assuming that our targets $y$ are given by a deterministic function $f(x,w)$ with additive Gaussian noise:
$$y = f(x,w) + \epsilon $$
We also assume that $f(x,w)$ is given by a linear combination of the inputs. In our case, we have that:
$$f(x,w) = w x $$

As you can seen, the function above is a line, where $w$ is its slope. However, we are forcing this line to go through zero, because when our input $x=0$ we have that we are predicting $f(x,w)=0$, which is not always the case. Indeed, it is difficult to have centered data in a real-word application. To overcome this drawback, we learn also a bias, which represents the intercept of our line. Therefore, we have:

\begin{align}
f(x,w) &= b + wx\\
&= b * 1 + w * x 
\end{align}

This corresponds to considering our dataset being made of $\mathbf{x}= [1, x ]$ and we want to learn the following weights $\mathbf{w}= [b, w ]$. Note that the bias is usually denoted with $w_0$ in most of the books.

However, if we center the data, the bias or intercept is not useful anymore, because it forces it to be 0. 

In the exercise we start by adding the column of 1s in front of the dataset because this is the typical thing to do in linear regression (as centered data is typically not required). But since the GP typically assumes centering we here use centered dataset and a bias term for the linear regression to keep thing compatible.








In [2]:
## we have to create our dataset
real_weights = np.array([3.24, 1.27, -4.52, 1.75])

# number of observations
N = 100
# dimension of X
d = 3
X = np.random.rand(N,d) * np.random.randint(1,20,(N,d)) # Nxd matrix

# we add the bias term adding a column of 1 in front
# of our matrix X
X = np.hstack((np.ones((N,1)), X)) # Nx(d+1)

# compute the y's for each example
# noisy --> add random noise
y = real_weights @ X.T + np.random.randn(N)# N

# now we can split the dataset in training and test set
Xtrain = X[:80,:]
ytrain = y[:80]

Xtest = X[80:,:]
ytest = y[80:]

print('Safety check: sizes')
print(Xtrain.shape)
print(ytrain.shape)
print(Xtest.shape)
print(ytest.shape)


Safety check: sizes
(80, 4)
(80,)
(20, 4)
(20,)


### Conditional Gaussian

We start by assuming that

$$\begin{bmatrix} y \\ \mathbf{x} \end{bmatrix} \sim \mathcal{N}\left(\mathbf{0}, \begin{bmatrix} \Sigma_{yy} & \Sigma_{yx} \\ \Sigma_{xy} & \Sigma{xx} \end{bmatrix} \right) $$

where $\Sigma_{yy} \in \mathbb{R}$ and $\Sigma_{yy} = \sigma_{y}^2$, i.e. it is the variance of the $y$ because $y \in \mathbb{R}$. $\Sigma_{xx}$ is instead the covariance matrix related to the input vectors $\mathbf{x}$. 

<font color='blue'>Tasks:</font>

<font color='blue'>**1-** Since we are assuming a zero-mean distribution, we should center or standardize our data. </font>

<font color='blue'>**2-** In the distribution above, we are considering the distribution of a vector created by concatenating the training target $y_i$ to each training input $\mathbf{x}_i$. Have a look at the python function `numpy.hstack` to implement this step.</font>

<font color='blue'>**3-** At this point you can compute the sample mean and the sample covariance of this distribution. Be careful and read the documentation of `np.cov`.</font>

In [3]:
# we assume that the traning data (y,x) ~ N(0,\Sigma)
# to have 0 mean we have to center the data

## WRITE THE CODE TO CENTER THE Xs
Xtrain_mean = np.mean(Xtrain,0)
Xtrain = Xtrain - Xtrain_mean

## WRITE THE CODE TO CENTER THE Xs
ytrain_mean = np.mean(ytrain)
ytrain = ytrain - ytrain_mean

# create arrays [y,x1,x2,...,xd] for each array
dataset = np.hstack((ytrain.reshape(-1,1), Xtrain))

print('Safety check') # you should get a shape of (80, 5)
print(dataset.shape)


# COMPUTE THE SAMPLE MEAN AND SAMPLE COVARIANCE
mu_dataset = np.mean(dataset,0)
cov_dataset = np.cov(dataset.T)         # you should get a dxd matrix
print(cov_dataset)

Safety check
(80, 5)
[[343.24799378   0.          32.50261211 -58.70607735  22.79886234]
 [  0.           0.           0.           0.           0.        ]
 [ 32.50261211   0.          21.44406901  -0.76748204   1.12534035]
 [-58.70607735   0.          -0.76748204  13.14917366   0.59349468]
 [ 22.79886234   0.           1.12534035   0.59349468  14.09736946]]


At this point we have the distribution of $\begin{bmatrix} y \\ \mathbf{x} \end{bmatrix}$ defined above. However, we are interested in the conditional probability $y|\mathbf{x}$. We know from the lecture that the conditional distribution of a Gaussian distribution is still a Gaussian distribution. 

Therefore we are looking for:

$$y | \mathbf{x} \sim \mathcal{N}(\mathbf{\mu}_{y|\mathbf{x}}, \Sigma_{y|\mathbf{x}})$$

where

$$\mathbf{\mu}_{y|\mathbf{x}} = \mu_{y} + \Sigma_{yx}\Sigma_{xx}^{-1}(\mathbf{x}-\mu_{x}) $$

$$\Sigma_{y|\mathbf{x}} = \Sigma_{yy} - \Sigma_{yx}\Sigma_{xx}^{-1}\Sigma_{xy}$$

Since we have centered our data, we have that both $\mu_{y} = 0$ and $\mu_{x}= 0$. Therefore, the equation for computing the $\mathbf{\mu}_{y|\mathbf{x}}$ becomes easier:

$$\mathbf{\mu}_{y|\mathbf{x}} = \Sigma_{yx}\Sigma_{xx}^{-1}\mathbf{x} $$

We are mostly interested in the mean of this distribution, because it is the one that give us the mean estimate for every input $\mathbf{x}$. Indeed. if we look at the definition of the mean we can see that it is a linear function of the inputs $\mathbf{x}$. For simplicity you can write it as $\mathbf{\mu}_{y|\mathbf{x}} = \mathbf{c} \mathbf{x}$, where $\mathbf{c}=\Sigma_{yx}\Sigma_{xx}^{-1}$. As we are going to see later, this is really similar to what we get when we are using a linear model for predictions. 


<font color='blue'>Tasks:</font>

<font color='blue'> **1**- Starting from the mean and covariance you have computed at the previous step, you should compute the vector $\mathbf{c}=\Sigma_{yx}\Sigma_{xx}^{-1}$, because if we know its value, we are able to compute the value of the mean $\mathbf{\mu}_{y|\mathbf{x}}^*$ for every test input vectors $\mathbf{x}_*$. To compute the inverse of a matrix you can use `np.linalg.pinv`.</font>

In [4]:
# we are interested in p(y|x1,..xd) which is Gaussian given by
# mu_yx = Sigmayx Simgaxx^-1 x

# SEPARATE ALL THE PIECES IN THE COVARIANCE MATRIX
Sigma_yy = cov_dataset[0,0]
Sigma_yx = cov_dataset[0,1:]
Sigma_xy = cov_dataset[1:,0]
Sigma_xx = cov_dataset[1:,1:]


print('Safety check covariance')
print(Sigma_yy.shape)
print(Sigma_xy.shape)
print(Sigma_yx.shape)
print(Sigma_xx.shape)

## 

# COMPUTE THE INVERSE AND THEN DO THE MATRIX MULTIPLICATION \Sigmayx\Sigmaxx^-1
C = Sigma_yx @ np.linalg.pinv(Sigma_xx)

print('Safety check')
print(C.shape)
print('The C you find is: ', C)

Safety check covariance
()
(4,)
(4,)
(4, 4)
Safety check
(4,)
The C you find is:  [ 0.          1.26636126 -4.46762863  1.70423914]


In [5]:
print(cov_dataset)
print(cov_dataset.shape)

[[343.24799378   0.          32.50261211 -58.70607735  22.79886234]
 [  0.           0.           0.           0.           0.        ]
 [ 32.50261211   0.          21.44406901  -0.76748204   1.12534035]
 [-58.70607735   0.          -0.76748204  13.14917366   0.59349468]
 [ 22.79886234   0.           1.12534035   0.59349468  14.09736946]]
(5, 5)


### Linear models

<font color='grey'>  Notation alert! We are going to write summations in matrix notation, therefore you should be comfortable with using vectors and matrices. </font>


Here we are going to derive again the Normal Equation that you have already seen in your Machine Learning course. In regression, we usually try to learn a model of this form:
$$y = \mathbf{w}^T\mathbf{x}$$
where $\mathbf{w}=[w_0, w_1,\dotsc,w_D]$ and $\mathbf{x} = [1, x_0, x_1, \dotsc, x_D]$.

Given a dataset that contains $N$ training examples $(\mathbf{x}_i,y_i)_{i=1,\dotsc,N}$, we learn the weigths or parameters of the model $\mathbf{w}$ by minimizing the Mean-Squared Error of the dataset given by
$$ E(\mathbf{w}) = \frac{1}{2} \sum_{n=1}^{N}(y_n - \mathbf{w}^T\mathbf{x}_n)^2$$

We can rewrite $E(\mathbf{w})$ as
\begin{align}
E(\mathbf{w}) &= \frac{1}{2} \sum_{n=1}^{N}(y_n - \mathbf{w}^T\mathbf{x}_n)^2 \\
              &= \frac{1}{2} \left\| \mathbf{X}\mathbf{w} - \mathbf{y} \right\|^2 \\
              &= \frac{1}{2} (\mathbf{X}\mathbf{w} - \mathbf{y})^T(\mathbf{X}\mathbf{w} - \mathbf{y}) \\
              &= \frac{1}{2} \mathbf{w}^T\mathbf{X}^T\mathbf{X}\mathbf{w} - \frac{1}{2}\mathbf{w}^T\mathbf{X}^T\mathbf{y} - \frac{1}{2} \mathbf{y}^T\mathbf{X}\mathbf{w} + \frac{1}{2} \mathbf{y}^T\mathbf{y} \\
              &= \frac{1}{2} \mathbf{w}^T\mathbf{X}^T\mathbf{X}\mathbf{w} - \mathbf{w}^T\mathbf{X}^T\mathbf{y} + \frac{1}{2} \mathbf{y}^T\mathbf{y}
\end{align}

where in the last line we use the fact that $(\mathbf{X}\mathbf{w})^T \mathbf{y} = \mathbf{y}^T(\mathbf{X}\mathbf{w})$ because the inner product is commutative and the fact that $(\mathbf{X}\mathbf{w})^T=\mathbf{w}^T\mathbf{X}^T$.

Since we want to find the weights $\mathbf{w}$ that minimize $E(\mathbf{w})$, from calculus we know that to solve this problem we can take the gradient of $E(\mathbf{w})$, and then set it to zero and solve the resulting system. 
$$\nabla E(\mathbf{w}) = \begin{bmatrix} \frac{\partial E}{\partial w_0}\\ \frac{\partial E}{\partial w_1}\\ \vdots \\ \frac{\partial E}{\partial w_D} \end{bmatrix} = 0$$ 

Two compute the gradient we use two results that are important to know:
$$ f(\mathbf{w}) = \mathbf{w}^T\mathbf{A}\mathbf{w} \implies \nabla f(\mathbf{w}) = 2 \mathbf{A}\mathbf{w}$$
$$ f(\mathbf{w}) = \mathbf{a}^T\mathbf{w}  \implies \nabla f(\mathbf{w}) = \mathbf{a}$$

Therefore we can see that the gradient of $E(\mathbf{w})$ is given by:
$$\nabla E(\mathbf{w}) = \mathbf{X}^T \mathbf{X} \mathbf{w} - \mathbf{X}^T\mathbf{y} $$
and if we put this to zero we get
\begin{align}
\mathbf{X}^T \mathbf{X} \mathbf{w} - \mathbf{X}^T\mathbf{y} = 0 \\
\mathbf{X}^T \mathbf{X} \mathbf{w} = \mathbf{X}^T\mathbf{y} \\
\mathbf{w}  = (\mathbf{X}^T \mathbf{X})^{-1}\mathbf{X}^T\mathbf{y} 
\end{align}

<font color='blue'> Tasks:</font>

<font color='blue'> **1**- You should code the normal equation in Python. The easiest way to compute it is to write all the matrix multiplication as shown in the formula. Remember, if you want to compute the inverse of a matrix use `numpy.linalg.pinv`. </font>

<font color='blue'> (There are other ways you can maybe implement the normal equation, but for this exercise we required you to use the easiest one. You maybe notice that you are trying to solve a linear system, therefore you would try to use `numpy.linalg.solve`. However, in case our system is either over or underconstrained this method will return an error. In those cases you can consider `numpy.linalg.lstsq` which will return the solution that minimizes the squared error.) </font>



In [6]:
# WRITE THE NORMAL EQUATION

w = np.linalg.pinv(Xtrain.T @ Xtrain) @ Xtrain.T @ ytrain

print('The weigths obtained by solving the normal equation are:', w)


The weigths obtained by solving the normal equation are: [ 0.          1.26636126 -4.46762863  1.70423914]


### Predictions

You have already seen in previous courses how to compute the prediction $y_*$ for a test example $\mathbf{x}_*$:
$$y_* = \mathbf{w}^T \mathbf{x}_*$$
using the weights you have computed in the previous step.

Maybe you have not seen before that you can use multivariate Gaussian distribution to make predictions. For predicting the target $y_*$ for a particular test input $x_*$ you should use the conditional Gaussian distribution $y_*|\mathbf{x}_*$, that you have computed above. Indeed, you want to compute the distribution of the possible targets $y_*$ given the test input $x_*$. A good estimate of $y_*$ would be the mean of this distribution, therefore you should compute:
$$y_* = \mu_{y_*|\mathbf{x}_*} = \Sigma_{yx}\Sigma_{xx}^{-1}\mathbf{x}_*$$
where the $\Sigma_{yx}$ and $\Sigma_{xx}$ are those you have calculated from the training set.

<font color='blue'>Tasks: </font>

<font color='blue'> **1**- For each test point, you should compute the prediction given by the linear model and the mena of the conditional distribution, and plot it. What do you notice? 

**N.B**: Remember that every modifications you did in the training set should be done also in the test set. This means that  you should center each test set (both the input $\mathbf{x}_*$ and the true target $y$ using the means you have computed in the training set!) </font>



In [7]:
# CENTER THE TEST EXAMPLES
Xtest -= Xtrain_mean
ytest -= ytrain_mean

# COMPUTE THE PREDICTION USING THE LINEAR MODEL
yhat = Xtest @ w.T

# COMPUTE THE MEAN GIVEN BY THE CONDITIONAL GAUSSIAN
mu_hat = Xtest @ C

# PRINT THE RESULTS
columns = ('Example no.', 'y (true)', 'y_hat (lin. reg.)', 'mu(y|x) (cond. mean)')
print('    '.join(columns))
for i, (y, yh, ym) in enumerate(zip(ytest, yhat, mu_hat)):
    print('{:11d}    {:8.2f}    {:17.2f}    {:20.2f}'.format(i+1, y, yh, ym))

Example no.    y (true)    y_hat (lin. reg.)    mu(y|x) (cond. mean)
          1       12.88                12.54                   12.54
          2       -7.98                -9.02                   -9.02
          3      -34.22               -34.70                  -34.70
          4       19.27                19.45                   19.45
          5       -1.26                -0.49                   -0.49
          6      -38.13               -39.66                  -39.66
          7       15.70                13.94                   13.94
          8       -6.45                -8.91                   -8.91
          9       13.65                10.57                   10.57
         10        1.72                 1.43                    1.43
         11       -1.63                -1.10                   -1.10
         12        9.19                 9.32                    9.32
         13        2.49                 2.14                    2.14
         14       20.84           

### Why do we get this result?

<font color='blue'> From the results you get, what can you notice? Try to think at the possible reasons why you observe this findings! </font>

<font color='green'> ANSWER: To get an answer we should get at how the predictions are computed. For the linear model we have:
\begin{align}
y_* &= \mathbf{w}^T\mathbf{x}_* \\
y_* &= ( (\mathbf{X}^T \mathbf{X})^{-1}\mathbf{X}^T\mathbf{y} )^T\mathbf{x}_*
\end{align}
From this expression we immediately see that $\mathbf{X}^T \mathbf{X}$ (with appropriate scaling, $\tfrac{1}{N-1}$) is the covariance of the training points. Likewise, $\mathbf{X}^T\mathbf{y}$ (again with appropriate scaling, $\tfrac{1}{N-1}$) is the covariance between the training and test data. When we multiply the inverse training covariance and the train/test covariance the scaling factor, $\tfrac{1}{N-1}$, disappears and we see that the two expressions are identical. While this is sufficient to argue that the results are identical (given familiarity with calculating covariance for matrices/vectors), below a more elaborate derivation is given for the sake of completeness. 
    
To make a little easier, we denote $\mathbf{A}= (\mathbf{X}^T \mathbf{X})$ since it is a $(D+1) \times (D+1)$ matrix and $\mathbf{b} = \mathbf{X}^T\mathbf{y} $ which is a vector. Therefore, we can write the prediction in a linear model as:
\begin{align}
y_* &= (\mathbf{A}^{-1}\mathbf{b})^T\mathbf{x}_* \\
    &= \mathbf{b}^T (\mathbf{A}^{-1})^T\mathbf{x}_* \\
    &= \mathbf{b}^T (\mathbf{A}^T)^{-1}\mathbf{x}_*
\end{align}
where in the last line we use the fact that $(\mathbf{A}^{-1})^T = (\mathbf{A}^T)^{-1}$. </font>

<font color='green'> The vector $\mathbf{b}^T$ is a $1 \times (D+1)$ vector while the matrix $(\mathbf{A}^T)^{-1}$ is a $(D+1) \times (D+1)$ matrix. Their product is therefore a $1 \times (D+1)$ vector, as expected, given the linear model assumption of having the target being a linear combination of the input variables.</font>

<font color='green'>If we look now at the way the mean of the conditional distribution $\mu_{y_*|\mathbf{x}_*}$ is computed for a new example $\mathbf{x}_*$ we can notice that there is a correspondence with the linear models:
$$y_* = \mu_{y_*|\mathbf{x}_*} = \Sigma_{yx}\Sigma_{xx}^{-1}\mathbf{x}_*$$ </font>

<font color='green'>Indeed, also in this case we have a vector $\Sigma_{yx}$ which is the first row without the first element of the covariance matrix of the distribution of $\begin{bmatrix} y \\ \mathbf{x} \end{bmatrix}$ and the inverse of a matrix $\Sigma_{xx}^{-1}$ which represents the covariance of the distribution of $\begin{bmatrix} x_1 \\ \vdots \\ x_D \end{bmatrix}$. The vector-matrix multiplication results in a $1 \times (D+1)$ vector. Therefore also in this case we have that the mean, which we are using as prediction, is a linear combination of the input.  </font>

<font color='green'> We can try to see if there is really a link between $\mathbf{b}^T=\mathbf{y}^T\mathbf{X}$ and $\Sigma_{yx}$ and also between $\mathbf{A}= (\mathbf{X}^T \mathbf{X})$ and $\Sigma_{xx}$. </font>

<font color='green'>To do that, we should go through at how the sample covariance matrix is computed. We consider our vector $\begin{bmatrix} y \\ 1 \\ x_1 \\ x_2 \\ x_3 \end{bmatrix}$ and for make it more clear we define $\begin{bmatrix} y \\ x_0 \\ x_1 \\ x_2 \\ x_3 \end{bmatrix}$ we defined the column of 1 as $x_0$. The sample covariance among this $D+2$ variables based on $N$ observation of each, drawn from on unobserved population are given by the $D+2 \times D+2$ matrix where the entries $q_{jk}$ are computed as:</font>

<font color='green'>$$ q_{jk} = \frac{1}{N-1} \sum_{i=1}^{N}(x_{j}^{(i)} - \mu_j)(x_{k}^{(i)} - \mu_k)$$ </font>

<font color='green'> and since in our case we center the data we can write this as</font>

<font color='green'>$$ q_{jk} = \frac{1}{N-1} \sum_{i=1}^{N}x_{j}^{(i)}x_{k}^{(i)}$$ </font>

<font color='green'> We can write the covariance matrix in our case as:</font>

<font color='green'> $$ \Sigma = \begin{bmatrix} q_{y,y} & q_{y x_0} & q_{y, x_1} & q_{y x_2} & q_{y x_3} \\ q_{x_0,y} & q_{x_0,x_0} & q_{x_0,x_1} & q_{x_0, x_2} & q_{x_0, x_3} \\ q_{x_1, y} & q_{x_1, x_0} & q_{x_1, x_1} & q_{x_1, x_2} & q_{x_1, x_3} \\ q_{x_2, y} & q_{x_2, x_0} & q_{x_2, x_1} & q_{x_2, x_2} & q_{x_2, x_3} \\ q_{x_3, y} & q_{x_3, x_0} & q_{x_3, x_1} & q_{x_3, x_2} & q_{x_3, x_3} \end{bmatrix} $$ </font>

<font color='green'> Where we can separates the quantities of our interest, i.e. $\Sigma_{yx}$ which we know that it is a vector and the sub-matrix $\Sigma_{xx}$:</font>

<font color='green'>$$ \Sigma_{yx} = [q_{y x_0}, q_{y, x_1}, q_{y x_2},  q_{y x_3}]$$
    
$$ \Sigma_{xx} = \begin{bmatrix} q_{x_0,x_0} & q_{x_0,x_1} & q_{x_0, x_2} & q_{x_0, x_3} \\ q_{x_1, x_0} & q_{x_1, x_1} & q_{x_1, x_2} & q_{x_1, x_3} \\ q_{x_2, x_0} & q_{x_2, x_1} & q_{x_2, x_2} & q_{x_2, x_3} \\  q_{x_3, x_0} & q_{x_3, x_1} & q_{x_3, x_2} & q_{x_3, x_3} \end{bmatrix} $$</font>

<font color='green'>We start considering $\Sigma_{yx}$. We can see that:</font>


<font color='green'>\begin{align}
\Sigma_{yx} &= [q_{y x_0}, q_{y, x_1}, q_{y x_2},  q_{y x_3}] \\
            &= [\frac{1}{N-1} \sum_{i=1}^{N}y^{(i)}x_{0}^{(i)}, \frac{1}{N-1} \sum_{i=1}^{N}y^{(i)}x_{1}^{(i)}, \frac{1}{N-1} \sum_{i=1}^{N}y^{(i)}x_{2}^{(i)}, \frac{1}{N-1} \sum_{i=1}^{N}y^{(i)}x_{3}^{(i)}] \\
            &= [\frac{1}{N-1} (y^{(0)}x_{0}^{(0)}+y^{(1)}x_{0}^{(1)}+\dotsc+y^{(N)}x_{0}^{(N)}), \frac{1}{N-1} (y^{(0)}x_{1}^{(0)}+y^{(1)}x_{1}^{(1)}+\dotsc+y^{(N)}x_{1}^{(N)}), \frac{1}{N-1} (y^{(0)}x_{2}^{(0)}+y^{(1)}x_{2}^{(1)}+\dotsc+y^{(N)}x_{2}^{(N)}), \frac{1}{N-1} (y^{(0)}x_{3}^{(0)}+y^{(1)}x_{3}^{(1)}+\dotsc+y^{(N)}x_{3}^{(N)})]\\
            &= \frac{1}{N-1} [\mathbf{y}^T \mathbf{x}_0, \mathbf{y}^T \mathbf{x}_1, \mathbf{y}^T \mathbf{x}_2, \mathbf{y}^T \mathbf{x}_3]\\
            &= \frac{1}{N-1} \mathbf{y}^T\mathbf{X}
\end{align}</font>

<font color='green'>Therefore, we can see that $\Sigma_{yy}$ is exactly the same as vector $\mathbf{b}^T=\mathbf{y}^T\mathbf{X}$ used in linear models for predicting a test target. </font>


<font color='green'>The steps to shows that also $\Sigma_{xx}$ is equal to $\mathbf{A}= (\mathbf{X}^T \mathbf{X})$ are similar, but a bit longer because it is a matrix. </font>

